from config import DB_TYPE
from database.db import get_conn, init_db


def seed_data():
    init_db()
    conn = get_conn()
    cur = conn.cursor()

    place = "%s" if DB_TYPE == "mysql" else "?"
    cur.execute(f"SELECT COUNT(*) as cnt FROM subjects")
    if cur.fetchone()["cnt"] > 0:
        return

    cur.execute(f"INSERT INTO subjects (name, display_name, icon) VALUES ({place}, {place}, {place})",
                ("english", "考研英语", "📖"))
    cur.execute(f"INSERT INTO subjects (name, display_name, icon) VALUES ({place}, {place}, {place})",
                ("politics", "考研政治", "📚"))
    eng_id = 1
    pol_id = 2

    english_topics = [
        ("核心词汇 (高频词)", 1),
        ("核心词汇 (中频词)", 2),
        ("阅读真题词汇", 3),
        ("写作常用表达", 4),
        ("翻译高频词组", 5),
        ("完形填空搭配", 6),
    ]
    for name, order in english_topics:
        cur.execute(f"INSERT INTO topics (subject_id, name, order_num) VALUES ({place},{place},{place})",
                    (eng_id, name, order))

    politics_topics = [
        ("马克思主义基本原理", 1),
        ("毛泽东思想和中国特色社会主义", 2),
        ("中国近现代史纲要", 3),
        ("思想道德修养与法律基础", 4),
        ("形势与政策及当代世界经济与政治", 5),
    ]
    for name, order in politics_topics:
        cur.execute(f"INSERT INTO topics (subject_id, name, order_num) VALUES ({place},{place},{place})",
                    (pol_id, name, order))

    english_cards = {
        1: [
            ("abandon", "v. 放弃；遗弃\nn. 放任，放纵"),
            ("absorb", "v. 吸收；吸引（注意）"),
            ("abstract", "adj. 抽象的；理论上的\nn. 摘要"),
            ("academic", "adj. 学术的；学院的\nn. 大学教师"),
            ("accelerate", "v. 加速；促进"),
            ("access", "n. 通道；机会\nv. 访问"),
            ("accommodate", "v. 容纳；提供住处"),
            ("accompany", "v. 陪伴；伴随"),
            ("accomplish", "v. 完成；实现"),
            ("accurate", "adj. 准确的；精确的"),
            ("accuse", "v. 指控；谴责"),
            ("achieve", "v. 达到；取得"),
            ("acknowledge", "v. 承认；确认"),
            ("acquire", "v. 获得；学到"),
            ("adapt", "v. 适应；改编"),
            ("adequate", "adj. 充足的；适当的"),
            ("adjust", "v. 调整；适应"),
            ("administration", "n. 管理；行政"),
            ("adopt", "v. 采用；收养"),
            ("advance", "v. 前进；促进\nn. 进步"),
            ("adverse", "adj. 不利的；相反的"),
            ("advocate", "v. 提倡\nn. 提倡者"),
            ("affect", "v. 影响；感动"),
            ("aggregate", "v. 总计；聚集"),
            ("allocate", "v. 分配；拨出"),
            ("alternative", "n. 替代物\nadj. 替代的"),
            ("ambiguous", "adj. 模糊的；含糊的"),
            ("ambitious", "adj. 有雄心的"),
            ("analysis", "n. 分析；解析"),
            ("anticipate", "v. 预期；期望"),
            ("apparent", "adj. 明显的"),
            ("appeal", "v. 呼吁；吸引\nn. 吸引力"),
            ("application", "n. 申请；应用"),
            ("approach", "v. 接近\nn. 方法；途径"),
            ("appropriate", "adj. 适当的"),
            ("approve", "v. 批准；赞成"),
            ("arise", "v. 出现；产生"),
            ("assign", "v. 分配；指派"),
            ("associate", "v. 联系；联想"),
            ("assume", "v. 假定；承担"),
            ("attach", "v. 附上；连接"),
            ("attempt", "v. 尝试\nn. 努力"),
            ("attitude", "n. 态度；看法"),
            ("attract", "v. 吸引；引起"),
            ("authority", "n. 权威；权力"),
            ("available", "adj. 可用的；有效的"),
            ("barrier", "n. 障碍；屏障"),
            ("benefit", "n. 利益\nv. 有益于"),
            ("budget", "n. 预算\nadj. 廉价的"),
            ("capability", "n. 能力；才能"),
        ],
        2: [
            ("capacity", "n. 能力；容量"),
            ("capture", "v. 捕获；引起"),
            ("category", "n. 类别；种类"),
            ("cause", "n. 原因\nv. 引起"),
            ("challenge", "n. 挑战\nv. 向……挑战"),
            ("characteristic", "n. 特征\nadj. 典型的"),
            ("circumstance", "n. 环境；情况"),
            ("claim", "v. 声称；要求\nn. 主张"),
            ("clarify", "v. 澄清；阐明"),
            ("classify", "v. 分类；归类"),
            ("climate", "n. 气候；风气"),
            ("collapse", "v. 倒塌；崩溃"),
            ("command", "v. 命令；指挥"),
            ("comment", "n. 评论\nv. 评论"),
            ("commit", "v. 犯罪；承诺"),
            ("communicate", "v. 交流；传达"),
            ("community", "n. 社区；团体"),
            ("companion", "n. 同伴；伙伴"),
            ("compare", "v. 比较；对比"),
            ("compel", "v. 强迫；迫使"),
            ("compensate", "v. 补偿；赔偿"),
            ("competent", "adj. 有能力的"),
            ("competitive", "adj. 竞争的"),
            ("complaint", "n. 投诉；抱怨"),
            ("complex", "adj. 复杂的"),
            ("component", "n. 组成部分"),
            ("compose", "v. 组成；创作"),
            ("comprehension", "n. 理解力"),
            ("comprehensive", "adj. 全面的；综合的"),
            ("concentrate", "v. 集中；专注"),
            ("concept", "n. 概念；观念"),
            ("concern", "n. 关心\nv. 涉及"),
            ("conclude", "v. 结束；推断"),
            ("concrete", "adj. 具体的；有形的"),
            ("conduct", "v. 引导；实施\nn. 行为"),
            ("conference", "n. 会议；讨论会"),
            ("confident", "adj. 自信的"),
            ("confirm", "v. 确认；证实"),
            ("conflict", "n. 冲突；矛盾"),
            ("conscious", "adj. 有意识的"),
            ("consequence", "n. 结果；后果"),
            ("conservative", "adj. 保守的"),
            ("considerable", "adj. 相当大的"),
            ("consist", "v. 由……组成"),
            ("consistent", "adj. 一致的"),
            ("constant", "adj. 不断的"),
            ("constitute", "v. 构成；组成"),
            ("construct", "v. 建造；构造"),
            ("consult", "v. 咨询；查阅"),
            ("consume", "v. 消费；消耗"),
        ],
        3: [
            ("contemporary", "adj. 当代的"),
            ("contradiction", "n. 矛盾；反驳"),
            ("contribute", "v. 贡献；导致"),
            ("controversy", "n. 争论；争议"),
            ("convention", "n. 惯例；大会"),
            ("convince", "v. 使确信；说服"),
            ("cooperate", "v. 合作；协作"),
            ("correspond", "v. 对应；通信"),
            ("crisis", "n. 危机"),
            ("criteria", "n. 标准（复数）"),
            ("crucial", "adj. 关键的"),
            ("cultivate", "v. 培养；陶冶"),
            ("curriculum", "n. 课程"),
            ("debate", "n. 辩论\nv. 辩论"),
            ("decade", "n. 十年"),
            ("decline", "v. 下降；拒绝\nn. 下降"),
            ("decorate", "v. 装饰"),
            ("decrease", "v. 减少\nn. 减少"),
            ("defeat", "v. 击败\nn. 失败"),
            ("defend", "v. 防御；辩护"),
            ("define", "v. 定义；界定"),
            ("definite", "adj. 明确的"),
            ("deliberate", "adj. 故意的；深思熟虑的"),
            ("delicate", "adj. 精致的；微妙的"),
            ("deliver", "v. 交付；发表"),
            ("demonstrate", "v. 证明；示范"),
            ("depict", "v. 描绘；描述"),
            ("deposit", "v. 存放；储蓄\nn. 存款"),
            ("deprive", "v. 剥夺"),
            ("derive", "v. 源于；获得"),
            ("deserve", "v. 应得；值得"),
            ("designate", "v. 指定；指派"),
            ("desperate", "adj. 绝望的；拼命的"),
            ("despite", "prep. 尽管"),
            ("destination", "n. 目的地"),
            ("destruction", "n. 破坏；毁灭"),
            ("determine", "v. 决定；确定"),
            ("develop", "v. 发展；开发"),
            ("device", "n. 设备；装置"),
            ("devote", "v. 致力于；奉献"),
            ("differentiate", "v. 区分；区别"),
            ("dimension", "n. 维度；方面"),
            ("discipline", "n. 学科；纪律"),
            ("discount", "n. 折扣\nv. 打折"),
            ("discriminate", "v. 歧视；辨别"),
            ("displace", "v. 取代；转移"),
            ("display", "v. 展示\nn. 展览"),
            ("distinct", "adj. 明显的；独特的"),
            ("distinguish", "v. 区分；辨别"),
            ("distribute", "v. 分配；分发"),
            ("diverse", "adj. 多样的"),
            ("domestic", "adj. 国内的"),
            ("dominate", "v. 主导；支配"),
            ("dramatic", "adj. 戏剧性的"),
            ("duration", "n. 持续时间"),
            ("dynamic", "adj. 动态的\nn. 动力"),
        ],
        4: [
            ("First and foremost", "首先，最重要的是"),
            ("It is widely acknowledged that", "人们普遍认为"),
            ("There is no denying that", "不可否认的是"),
            ("It goes without saying that", "不言而喻"),
            ("As far as I am concerned", "就我而言"),
            ("From my perspective", "从我的角度来看"),
            ("To put it another way", "换句话说"),
            ("On the contrary", "相反地"),
            ("In contrast", "相比之下"),
            ("As a matter of fact", "事实上"),
            ("In the final analysis", "归根结底"),
            ("Last but not least", "最后但同样重要"),
            ("In conclusion", "总之"),
            ("It is imperative that", "当务之急是"),
            ("Play a significant role in", "在……中起重要作用"),
            ("Give rise to", "导致；引起"),
            ("Take into account", "考虑到"),
            ("Be attributed to", "归因于"),
            ("Be confronted with", "面临；面对"),
        ],
        5: [
            ("account for", "解释；占……比例"),
            ("ascribe to", "归因于"),
            ("attribute to", "归因于"),
            ("break down", "分解；出故障"),
            ("bring about", "引起；导致"),
            ("by contrast", "相比之下"),
            ("carry out", "执行；实施"),
            ("come up with", "提出；想出"),
            ("consist of", "由……组成"),
            ("contribute to", "有助于；导致"),
            ("depend on", "依赖；取决于"),
            ("draw on", "利用；凭借"),
            ("engage in", "从事；参与"),
            ("figure out", "弄明白；计算出"),
            ("give rise to", "引起；导致"),
            ("in terms of", "就……而言"),
            ("lay off", "解雇；停止"),
            ("make sense", "有意义；讲得通"),
            ("point of view", "观点；看法"),
            ("put forward", "提出；推荐"),
            ("refer to", "参考；指的是"),
            ("result in", "导致；造成"),
            ("set about", "开始；着手"),
            ("take over", "接管；接收"),
            ("turn out", "结果是；生产"),
            ("work out", "解决；制定出"),
        ],
        6: [
            ("on the whole", "总的来说"),
            ("in general", "一般来说"),
            ("for instance", "例如"),
            ("such as", "比如"),
            ("as a result", "因此"),
            ("in addition", "此外"),
            ("furthermore", "而且；此外"),
            ("nevertheless", "然而；不过"),
            ("nonetheless", "尽管如此"),
            ("otherwise", "否则；不然"),
            ("provided that", "假如；如果"),
            ("regardless of", "不管；不顾"),
            ("in spite of", "尽管"),
            ("due to", "由于"),
            ("owing to", "因为；由于"),
            ("thanks to", "幸亏；由于"),
            ("with respect to", "关于；至于"),
            ("on behalf of", "代表"),
            ("in favor of", "支持；赞成"),
            ("in light of", "鉴于；根据"),
        ],
    }

    politics_cards = {
        1: [
            ("马克思主义的创立", "1848年《共产党宣言》发表，标志着马克思主义的诞生。"),
            ("马克思主义的基本特征", "科学性、革命性、实践性、人民性和发展性。"),
            ("物质与意识的关系", "物质决定意识，意识对物质具有能动的反作用。"),
            ("唯物辩证法总特征", "联系的观点和发展的观点。"),
            ("对立统一规律", "事物发展的根本规律，是唯物辩证法的实质和核心。"),
            ("质量互变规律", "量变是质变的必要准备，质变是量变的必然结果。"),
            ("否定之否定规律", "事物发展是前进性和曲折性的统一。"),
            ("实践是认识的基础", "实践是认识的来源、动力、目的和检验标准。"),
            ("真理的绝对性与相对性", "真理是具体的、有条件的；绝对真理与相对真理辩证统一。"),
            ("社会存在与社会意识", "社会存在决定社会意识，社会意识具有相对独立性。"),
            ("生产力与生产关系", "生产力决定生产关系，生产关系反作用于生产力。"),
            ("经济基础与上层建筑", "经济基础决定上层建筑，上层建筑反作用于经济基础。"),
            ("社会基本矛盾", "生产力与生产关系的矛盾、经济基础与上层建筑的矛盾。"),
            ("人民群众是历史的创造者", "人民群众是社会物质财富、精神财富的创造者，是社会变革的决定力量。"),
            ("商品二因素", "商品是使用价值和价值的统一体。"),
            ("劳动二重性", "具体劳动创造使用价值，抽象劳动创造价值。"),
            ("价值规律", "商品的价值量由社会必要劳动时间决定，等价交换。"),
            ("剩余价值", "资本家剥削工人创造的超过劳动力价值的那部分价值。"),
            ("资本循环与周转", "产业资本依次经过购买、生产、销售三个阶段。"),
            ("资本主义基本矛盾", "生产社会化与生产资料资本主义私人占有之间的矛盾。"),
        ],
        2: [
            ("毛泽东思想的形成", "1945年中共七大确立毛泽东思想为党的指导思想。"),
            ("新民主主义革命总路线", "无产阶级领导的，人民大众的，反对帝国主义、封建主义和官僚资本主义的革命。"),
            ("新民主主义三大纲领", "政治纲领：建立无产阶级领导的各革命阶级联合专政；经济纲领：没收封建地主土地归农民所有；文化纲领：民族的科学的大众的文化。"),
            ("中国革命道路", "农村包围城市、武装夺取政权。"),
            ("三大法宝", "统一战线、武装斗争、党的建设。"),
            ("社会主义改造", "对农业、手工业和资本主义工商业的社会主义改造。"),
            ("社会主义初级阶段", "我国正处于并将长期处于社会主义初级阶段。"),
            ("习近平新时代中国特色社会主义思想", "是马克思主义中国化的最新成果，是当代中国马克思主义、21世纪马克思主义。"),
            ("中国式现代化", "人口规模巨大、全体人民共同富裕、物质文明和精神文明相协调、人与自然和谐共生、走和平发展道路的现代化。"),
            ("新发展理念", "创新、协调、绿色、开放、共享。"),
            ("新发展格局", "以国内大循环为主体、国内国际双循环相互促进。"),
            ("高质量发展", "是全面建设社会主义现代化国家的首要任务。"),
            ("总体国家安全观", "以人民安全为宗旨，以政治安全为根本。"),
            ("全过程人民民主", "社会主义民主政治的本质属性。"),
            ("一带一路", "丝绸之路经济带和21世纪海上丝绸之路。"),
        ],
        3: [
            ("鸦片战争", "1840年，中国近代史的开端，标志着中国开始沦为半殖民地半封建社会。"),
            ("太平天国运动", "1851-1864年，农民阶级的反封建反侵略斗争。"),
            ("洋务运动", "1860-1890年代，\"自强\"\"求富\"，是中国近代化的起步。"),
            ("戊戌变法", "1898年，资产阶级维新派发起的救亡图存运动。"),
            ("辛亥革命", "1911年，孙中山领导的资产阶级民主革命，推翻封建帝制。"),
            ("五四运动", "1919年，新民主主义革命的开端，标志着中国工人阶级登上政治舞台。"),
            ("中共一大", "1921年，中国共产党成立。"),
            ("南昌起义", "1927年8月1日，打响武装反抗国民党反动派第一枪。"),
            ("遵义会议", "1935年，确立毛泽东的领导地位，是党的历史上生死攸关的转折点。"),
            ("抗日战争", "1931-1945年，中国近代以来第一次取得完全胜利的民族解放战争。"),
            ("开国大典", "1949年10月1日，中华人民共和国成立。"),
            ("改革开放", "1978年十一届三中全会，开启了改革开放和社会主义现代化建设新时期。"),
            ("南方谈话", "1992年邓小平南方谈话，推动改革开放进入新阶段。"),
            ("香港回归", "1997年7月1日，中华人民共和国恢复对香港行使主权。"),
            ("澳门回归", "1999年12月20日，中华人民共和国恢复对澳门行使主权。"),
        ],
        4: [
            ("社会主义核心价值观", "富强、民主、文明、和谐；自由、平等、公正、法治；爱国、敬业、诚信、友善。"),
            ("社会主义道德核心", "为人民服务是社会主义道德的核心。"),
            ("社会主义道德原则", "集体主义是社会主义道德的原则。"),
            ("中华民族精神", "以爱国主义为核心的团结统一、爱好和平、勤劳勇敢、自强不息。"),
            ("时代精神", "以改革创新为核心。"),
            ("法律的本质", "法律是统治阶级意志的体现，是由国家制定或认可的行为规范。"),
            ("宪法基本原则", "党的领导原则、人民主权原则、尊重和保障人权原则、民主集中制原则、法治原则。"),
            ("公民基本权利", "平等权、政治权利、人身自由、社会经济权利、文化教育权利等。"),
            ("公民基本义务", "维护国家统一和民族团结、遵守宪法法律、依法纳税等。"),
            ("全面推进依法治国", "科学立法、严格执法、公正司法、全民守法。"),
            ("中国特色社会主义法治道路", "坚持党的领导、坚持人民主体地位、坚持法律面前人人平等。"),
            ("法治思维", "将法律作为判断是非和处理事务的准绳。"),
        ],
        5: [
            ("和平与发展", "当今时代的主题。"),
            ("经济全球化", "世界经济活动超越国界，通过对外贸易、资本流动等形成的相互依存、相互联系的趋势。"),
            ("多极化趋势", "世界格局向多极化方向发展，多个力量中心相互制衡。"),
            ("人类命运共同体", "倡导建设持久和平、普遍安全、共同繁荣、开放包容、清洁美丽的世界。"),
            ("全球治理观", "共商共建共享的全球治理观。"),
            ("新型国际关系", "相互尊重、公平正义、合作共赢。"),
            ("中国外交政策", "独立自主的和平外交政策。"),
            ("一带一路倡议", "秉持共商共建共享原则，推动政策沟通、设施联通、贸易畅通、资金融通、民心相通。"),
            ("文明交流互鉴", "文明因多样而交流，因交流而互鉴，因互鉴而发展。"),
            ("生物安全", "国家安全体系的重要组成部分。"),
        ],
    }

    for topic_id, cards in english_cards.items():
        for idx, (front, back) in enumerate(cards):
            cur.execute(
                f"INSERT INTO cards (topic_id, front, back, order_num) VALUES ({place},{place},{place},{place})",
                (topic_id, front, back, idx + 1),
            )

    for topic_id, cards in politics_cards.items():
        for idx, (front, back) in enumerate(cards):
            cur.execute(
                f"INSERT INTO cards (topic_id, front, back, order_num) VALUES ({place},{place},{place},{place})",
                (topic_id + len(english_topics), front, back, idx + 1),
            )

    if DB_TYPE == "mysql":
        conn.commit()
