from config import DB_TYPE
from database.db import get_conn, init_db


def seed_data():
    init_db()
    conn = get_conn()
    cur = conn.cursor()

    place = "%s" if DB_TYPE == "mysql" else "?"
    cur.execute(f"SELECT COUNT(*) as cnt FROM subjects")
    if cur.fetchone()["cnt"] > 0:
        return

    cur.execute(f"INSERT INTO subjects (name, display_name, icon) VALUES ({place}, {place}, {place})",
                ("english", "考研英语", "📖"))
    cur.execute(f"INSERT INTO subjects (name, display_name, icon) VALUES ({place}, {place}, {place})",
                ("politics", "考研政治", "📚"))
    eng_id = 1
    pol_id = 2

    # Books
    cur.execute(f"INSERT INTO books (subject_id, name, order_num) VALUES ({place},{place},{place})",
                (eng_id, "红宝书·考研英语词汇", 1))
    cur.execute(f"INSERT INTO books (subject_id, name, order_num) VALUES ({place},{place},{place})",
                (eng_id, "考研英语词汇全攻略", 2))
    cur.execute(f"INSERT INTO books (subject_id, name, order_num) VALUES ({place},{place},{place})",
                (pol_id, "考研政治核心考案", 1))
    book_hongbao = 1
    book_english = 2
    book_politics = 3

    english_topics = [
        ("核心词汇 (高频词)", 1),
        ("核心词汇 (中频词)", 2),
        ("阅读真题词汇", 3),
        ("写作常用表达", 4),
        ("翻译高频词组", 5),
        ("完形填空搭配", 6),
    ]
    for name, order in english_topics:
        cur.execute(f"INSERT INTO topics (subject_id, book_id, name, order_num) VALUES ({place},{place},{place},{place})",
                    (eng_id, book_english, name, order))

    hongbao_topics = [
        ("基础词汇 Unit 1", 1), ("基础词汇 Unit 2", 2), ("基础词汇 Unit 3", 3),
        ("核心词汇 Unit 1", 4), ("核心词汇 Unit 2", 5), ("核心词汇 Unit 3", 6),
        ("超纲词汇", 7),
    ]
    for name, order in hongbao_topics:
        cur.execute(f"INSERT INTO topics (subject_id, book_id, name, order_num) VALUES ({place},{place},{place},{place})",
                    (eng_id, book_hongbao, name, order))

    politics_topics = [
        ("马克思主义基本原理", 1),
        ("毛泽东思想和中国特色社会主义", 2),
        ("中国近现代史纲要", 3),
        ("思想道德修养与法律基础", 4),
        ("形势与政策及当代世界经济与政治", 5),
    ]
    for name, order in politics_topics:
        cur.execute(f"INSERT INTO topics (subject_id, book_id, name, order_num) VALUES ({place},{place},{place},{place})",
                    (pol_id, book_politics, name, order))

    english_cards = {
        1: [
            ("abandon", "/əˈbændən/", "v. 放弃；遗弃；抛弃\nn. 放任；放纵",
             "They had to abandon the project due to lack of funds. 由于缺乏资金，他们不得不放弃这个项目。",
             "【用法】abandon sth/sb 放弃某物/抛弃某人\n【同义】give up, desert, forsake\n【反义】keep, retain, maintain"),
            ("absorb", "/əbˈzɔːrb/", "v. 吸收；吸引（注意）；使专心；吸纳",
             "The company will absorb all the costs. 公司将承担所有费用。",
             "【用法】be absorbed in 全神贯注于\n【同义】take in, soak up, engross\n【搭配】absorb knowledge 吸收知识"),
            ("abstract", "/ˈæbstrækt/", "adj. 抽象的；理论上的\nn. 摘要；抽象画\nv. 提取；摘录",
             "Truth is abstract and difficult to define. 真理是抽象的，难以定义。",
             "【用法】abstract noun 抽象名词\n【同义】theoretical, conceptual\n【反义】concrete, specific"),
            ("academic", "/ˌækəˈdemɪk/", "adj. 学术的；学院的；学业（好）的\nn. 大学教师；学者",
             "She had a brilliant academic career. 她拥有辉煌的学术生涯。",
             "【用法】academic year 学年\n【同义】scholarly, educational\n【搭配】academic research 学术研究"),
            ("accelerate", "/əkˈseləreɪt/", "v. 加速；促进；催促",
             "Economic growth has accelerated this year. 今年经济增长加速了。",
             "【用法】accelerate the pace of 加快……的步伐\n【同义】speed up, hasten, quicken\n【反义】decelerate, slow down"),
            ("access", "/ˈækses/", "n. 通道；机会；使用权\nv. 访问；存取",
             "Students need access to good libraries. 学生需要能使用好的图书馆。",
             "【用法】have access to 有机会使用/接近\n【同义】entry, admission"),
            ("accommodate", "/əˈkɒmədeɪt/", "v. 容纳；向……提供住处；使适应",
             "The hotel can accommodate up to 500 guests. 这家酒店可容纳500位客人。",
             "【用法】accommodate sb with sth 为某人提供某物\n【同义】hold, house, adapt"),
            ("accompany", "/əˈkʌmpəni/", "v. 陪伴；伴随；为……伴奏",
             "Please accompany me to the airport. 请陪我去机场。",
             "【用法】accompany sb to 陪伴某人去……\n【同义】escort, go with"),
            ("accomplish", "/əˈkʌmplɪʃ/", "v. 完成；实现；达到（目标）",
             "We have accomplished all our goals. 我们已实现所有目标。",
             "【用法】accomplish a task/goal 完成任务/实现目标\n【同义】achieve, complete, fulfill"),
            ("accurate", "/ˈækjərət/", "adj. 准确的；精确的；正确的",
             "Your information is not accurate. 你的信息不准确。",
             "【用法】accurate measurement 精确测量\n【同义】precise, exact, correct\n【反义】inaccurate, wrong"),
            ("accuse", "/əˈkjuːz/", "v. 指控；指责；谴责",
             "He was accused of stealing. 他被指控偷窃。",
             "【用法】accuse sb of (doing) sth 指控某人（做）某事\n【同义】blame, charge, indict"),
            ("achieve", "/əˈtʃiːv/", "v. 达到；取得；获得（成功）",
             "You can achieve anything if you work hard. 只要努力，你能实现任何目标。",
             "【用法】achieve success/goal 取得成功/实现目标\n【同义】accomplish, attain, reach"),
            ("acknowledge", "/əkˈnɒlɪdʒ/", "v. 承认；确认（收到）；致谢",
             "He acknowledged his mistake. 他承认了自己的错误。",
             "【用法】acknowledge doing sth 承认做了某事\n【同义】admit, recognize, accept"),
            ("acquire", "/əˈkwaɪər/", "v. 获得；学到；收购",
             "She acquired a good knowledge of English. 她学到了扎实的英语知识。",
             "【用法】acquire knowledge/skills 获得知识/技能\n【同义】gain, obtain, get"),
            ("adapt", "/əˈdæpt/", "v. 适应；改编；改写",
             "We must adapt to the changing world. 我们必须适应不断变化的世界。",
             "【用法】adapt (oneself) to 适应……\nadapt sth for 为……改编某物\n【同义】adjust, modify"),
            ("adequate", "/ˈædɪkwət/", "adj. 充足的；适当的；胜任的",
             "The supply is not adequate for the demand. 供不应求。",
             "【用法】be adequate for 足够……\nbe adequate to do 足以做……\n【同义】sufficient, enough, ample"),
            ("adjust", "/əˈdʒʌst/", "v. 调整；适应；校正",
             "You need to adjust your attitude. 你需要调整态度。",
             "【用法】adjust to 适应……\nadjust sth 调整某物\n【同义】adapt, regulate, modify"),
            ("administration", "/ədˌmɪnɪˈstreɪʃn/", "n. 管理；行政（部门）；政府（任期）",
             "The administration decided to cut taxes. 政府决定减税。",
             "【用法】business administration 工商管理\n【同义】management, government"),
            ("adopt", "/əˈdɒpt/", "v. 采用；采纳；收养",
             "The company adopted a new strategy. 公司采取了新策略。",
             "【用法】adopt a policy/approach 采取政策/方法\n【同义】embrace, take on, foster"),
            ("advance", "/ədˈvɑːns/", "v. 前进；促进；提出\nn. 进步；预付（款）",
             "Technology has advanced rapidly in recent years. 近年来技术进步迅速。",
             "【用法】in advance 提前\nadvance sth 推进某事\n【同义】progress, proceed, improve"),
            ("adverse", "/ˈædvɜːs/", "adj. 不利的；相反的；负面的",
             "The decision had adverse effects. 这个决定产生了负面影响。",
             "【用法】adverse conditions 不利条件\n【同义】unfavorable, negative, harmful\n【反义】favorable"),
            ("advocate", "/ˈædvəkeɪt/", "v. 提倡；主张；拥护\nn. 提倡者；拥护者",
             "Many people advocate for better healthcare. 许多人提倡改善医疗保健。",
             "【用法】advocate (doing) sth 提倡（做）某事\n【同义】support, promote, urge"),
            ("affect", "/əˈfekt/", "v. 影响；（使）感动；侵袭（疾病）",
             "The economic crisis affected millions of people. 经济危机影响了数百万人。",
             "【用法】be affected by 受……影响\n【同义】influence, impact, move"),
            ("aggregate", "/ˈæɡrɪɡət/", "v. 总计；聚集\nadj. 总计的；合计的",
             "The aggregate total reached one million. 总计数达到一百万。",
             "【用法】in the aggregate 总计；总的来说\n【同义】total, combined, overall"),
            ("allocate", "/ˈæləkeɪt/", "v. 分配；拨出（资金等）",
             "The government allocated funds for education. 政府拨出教育经费。",
             "【用法】allocate sth to 把某物分配给……\n【同义】assign, allot, distribute"),
            ("alternative", "/ɔːlˈtɜːnətɪv/", "n. 替代物；选择\nadj. 替代的；另类的",
             "We have no alternative but to leave. 我们别无选择，只能离开。",
             "【用法】have no alternative but to do 别无选择只能做……\n【同义】option, choice, substitute"),
            ("ambiguous", "/æmˈbɪɡjuəs/", "adj. 模糊的；含糊的；不明确的",
             "His statement was deliberately ambiguous. 他的陈述故意含糊其辞。",
             "【用法】ambiguous attitude 模糊态度\n【同义】vague, unclear, obscure\n【反义】clear, explicit"),
            ("ambitious", "/æmˈbɪʃəs/", "adj. 有雄心的；野心勃勃的；宏大的",
             "She is ambitious to become a CEO. 她雄心勃勃要当CEO。",
             "【用法】be ambitious to do 渴望做……\n【同义】aspiring, determined, driven"),
            ("analysis", "/əˈnæləsɪs/", "n. 分析；解析；（复数）analyses",
             "A detailed analysis of the data is needed. 需要对数据进行详细分析。",
             "【用法】in the final analysis 归根结底\n【同义】examination, study, evaluation"),
            ("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期；期望；预料",
             "We anticipate a big increase in sales. 我们预计销售额将大幅增长。",
             "【用法】anticipate (doing) sth 预料（做）某事\n【同义】expect, foresee, predict"),
            ("apparent", "/əˈpærənt/", "adj. 明显的；表面上的；显而易见的",
             "It became apparent that he was lying. 很明显他在撒谎。",
             "【用法】it is apparent that 很明显……\n【同义】obvious, evident, clear"),
            ("appeal", "/əˈpiːl/", "v. 呼吁；上诉；吸引\nn. 吸引力；恳求",
             "The idea appeals to young people. 这个想法吸引年轻人。",
             "【用法】appeal to 吸引；呼吁\nappeal against 对……上诉\n【同义】attract, plead, request"),
            ("application", "/ˌæplɪˈkeɪʃn/", "n. 申请（书）；应用；应用程序",
             "Fill in the application form first. 先填写申请表。",
             "【用法】application for 申请……\napplication of 应用……\n【同义】request, use, software"),
            ("approach", "/əˈprəʊtʃ/", "v. 接近；靠近；处理\nn. 方法；途径；接近",
             "We need a new approach to this problem. 我们需要新方法来处理这个问题。",
             "【用法】approach to (doing) sth （做）某事的方法\n【同义】method, way, manner"),
            ("appropriate", "/əˈprəʊpriət/", "adj. 适当的；合适的；恰当的",
             "Choose the appropriate words for the context. 选择适合语境的词语。",
             "【用法】be appropriate for 适合……\n【同义】suitable, proper, fitting\n【反义】inappropriate"),
            ("approve", "/əˈpruːv/", "v. 批准；赞成；认可",
             "The committee approved the plan. 委员会批准了该计划。",
             "【用法】approve of 赞成；同意\n【同义】endorse, sanction, accept\n【反义】reject, disapprove"),
            ("arise", "/əˈraɪz/", "v. 出现；产生；起源于（arose, arisen）",
             "Problems arose when the system failed. 系统故障时出现了问题。",
             "【用法】arise from/out of 由……引起\n【同义】emerge, occur, appear"),
            ("assign", "/əˈsaɪn/", "v. 分配；指派；指定",
             "The teacher assigned us a new task. 老师给我们分配了新任务。",
             "【用法】assign sth to sb 把某物分配给某人\n【同义】allocate, allot, designate"),
            ("associate", "/əˈsəʊʃieɪt/", "v. 联系；联想；交往\nn. 同事；伙伴",
             "We associate China with the Great Wall. 提到中国我们会联想到长城。",
             "【用法】associate with 与……有关联/交往\n【同义】connect, link, relate"),
            ("assume", "/əˈsjuːm/", "v. 假定；假设；承担（责任）",
             "I assume you know what you are doing. 我假定你知道自己在做什么。",
             "【用法】assume responsibility 承担责任\n【同义】presume, suppose, undertake"),
            ("attach", "/əˈtætʃ/", "v. 附上；连接；使依恋",
             "Please attach your resume to the email. 请将简历附在邮件中。",
             "【用法】attach importance to 重视\nbe attached to 附属于；依恋\n【同义】fasten, connect, affix"),
            ("attempt", "/əˈtempt/", "v. 尝试；企图\nn. 努力；尝试；攻击",
             "He attempted to climb the mountain alone. 他试图独自爬山。",
             "【用法】attempt to do 尝试做……\nin an attempt to do 为了……\n【同义】try, endeavor, effort"),
            ("attitude", "/ˈætɪtjuːd/", "n. 态度；看法；姿势",
             "We need a positive attitude toward life. 我们需要积极的生活态度。",
             "【用法】attitude to/toward 对……的态度\n【同义】viewpoint, outlook, stance"),
            ("attract", "/əˈtrækt/", "v. 吸引；引起；诱惑",
             "The museum attracts many visitors. 这家博物馆吸引了很多游客。",
             "【用法】attract attention 引起注意\n【同义】draw, lure, appeal to\n【反义】repel"),
            ("authority", "/ɔːˈθɒrəti/", "n. 权威；权力；当局（pl. authorities）",
             "The local authorities are investigating. 地方当局正在调查。",
             "【用法】have authority over 对……有管辖权\n【同义】power, jurisdiction, official"),
            ("available", "/əˈveɪləbl/", "adj. 可用的；有效的；空闲的",
             "Tickets are available at the box office. 售票处有票。",
             "【用法】be available to 可用于/可供……使用\n【同义】accessible, obtainable, free"),
            ("barrier", "/ˈbæriər/", "n. 障碍；屏障；关卡",
             "Language barrier is a common problem. 语言障碍是一个常见问题。",
             "【用法】trade barrier 贸易壁垒\n【同义】obstacle, hurdle, blockade"),
            ("benefit", "/ˈbenɪfɪt/", "n. 利益；好处；福利\nv. 有益于；受益",
             "Regular exercise benefits your health. 经常锻炼有益健康。",
             "【用法】benefit from 从……中受益\nfor the benefit of 为了……的利益\n【同义】advantage, profit, gain"),
            ("budget", "/ˈbʌdʒɪt/", "n. 预算\nv. 做预算\nadj. 廉价的；经济的",
             "The project is over budget. 项目超出预算了。",
             "【用法】within budget 在预算内\nbudget for 为……做预算\n【同义】financial plan, allowance"),
            ("capability", "/ˌkeɪpəˈbɪləti/", "n. 能力；才能；性能",
             "The system has the capability to handle large data. 该系统能够处理大数据。",
             "【用法】capability to do/of doing 做……的能力\n【同义】ability, capacity, competence"),
        ],
        2: [
            ("capacity", "n. 能力；容量"),
            ("capture", "v. 捕获；引起"),
            ("category", "n. 类别；种类"),
            ("cause", "n. 原因\nv. 引起"),
            ("challenge", "n. 挑战\nv. 向……挑战"),
            ("characteristic", "n. 特征\nadj. 典型的"),
            ("circumstance", "n. 环境；情况"),
            ("claim", "v. 声称；要求\nn. 主张"),
            ("clarify", "v. 澄清；阐明"),
            ("classify", "v. 分类；归类"),
            ("climate", "n. 气候；风气"),
            ("collapse", "v. 倒塌；崩溃"),
            ("command", "v. 命令；指挥"),
            ("comment", "n. 评论\nv. 评论"),
            ("commit", "v. 犯罪；承诺"),
            ("communicate", "v. 交流；传达"),
            ("community", "n. 社区；团体"),
            ("companion", "n. 同伴；伙伴"),
            ("compare", "v. 比较；对比"),
            ("compel", "v. 强迫；迫使"),
            ("compensate", "v. 补偿；赔偿"),
            ("competent", "adj. 有能力的"),
            ("competitive", "adj. 竞争的"),
            ("complaint", "n. 投诉；抱怨"),
            ("complex", "adj. 复杂的"),
            ("component", "n. 组成部分"),
            ("compose", "v. 组成；创作"),
            ("comprehension", "n. 理解力"),
            ("comprehensive", "adj. 全面的；综合的"),
            ("concentrate", "v. 集中；专注"),
            ("concept", "n. 概念；观念"),
            ("concern", "n. 关心\nv. 涉及"),
            ("conclude", "v. 结束；推断"),
            ("concrete", "adj. 具体的；有形的"),
            ("conduct", "v. 引导；实施\nn. 行为"),
            ("conference", "n. 会议；讨论会"),
            ("confident", "adj. 自信的"),
            ("confirm", "v. 确认；证实"),
            ("conflict", "n. 冲突；矛盾"),
            ("conscious", "adj. 有意识的"),
            ("consequence", "n. 结果；后果"),
            ("conservative", "adj. 保守的"),
            ("considerable", "adj. 相当大的"),
            ("consist", "v. 由……组成"),
            ("consistent", "adj. 一致的"),
            ("constant", "adj. 不断的"),
            ("constitute", "v. 构成；组成"),
            ("construct", "v. 建造；构造"),
            ("consult", "v. 咨询；查阅"),
            ("consume", "v. 消费；消耗"),
        ],
        3: [
            ("contemporary", "adj. 当代的"),
            ("contradiction", "n. 矛盾；反驳"),
            ("contribute", "v. 贡献；导致"),
            ("controversy", "n. 争论；争议"),
            ("convention", "n. 惯例；大会"),
            ("convince", "v. 使确信；说服"),
            ("cooperate", "v. 合作；协作"),
            ("correspond", "v. 对应；通信"),
            ("crisis", "n. 危机"),
            ("criteria", "n. 标准（复数）"),
            ("crucial", "adj. 关键的"),
            ("cultivate", "v. 培养；陶冶"),
            ("curriculum", "n. 课程"),
            ("debate", "n. 辩论\nv. 辩论"),
            ("decade", "n. 十年"),
            ("decline", "v. 下降；拒绝\nn. 下降"),
            ("decorate", "v. 装饰"),
            ("decrease", "v. 减少\nn. 减少"),
            ("defeat", "v. 击败\nn. 失败"),
            ("defend", "v. 防御；辩护"),
            ("define", "v. 定义；界定"),
            ("definite", "adj. 明确的"),
            ("deliberate", "adj. 故意的；深思熟虑的"),
            ("delicate", "adj. 精致的；微妙的"),
            ("deliver", "v. 交付；发表"),
            ("demonstrate", "v. 证明；示范"),
            ("depict", "v. 描绘；描述"),
            ("deposit", "v. 存放；储蓄\nn. 存款"),
            ("deprive", "v. 剥夺"),
            ("derive", "v. 源于；获得"),
            ("deserve", "v. 应得；值得"),
            ("designate", "v. 指定；指派"),
            ("desperate", "adj. 绝望的；拼命的"),
            ("despite", "prep. 尽管"),
            ("destination", "n. 目的地"),
            ("destruction", "n. 破坏；毁灭"),
            ("determine", "v. 决定；确定"),
            ("develop", "v. 发展；开发"),
            ("device", "n. 设备；装置"),
            ("devote", "v. 致力于；奉献"),
            ("differentiate", "v. 区分；区别"),
            ("dimension", "n. 维度；方面"),
            ("discipline", "n. 学科；纪律"),
            ("discount", "n. 折扣\nv. 打折"),
            ("discriminate", "v. 歧视；辨别"),
            ("displace", "v. 取代；转移"),
            ("display", "v. 展示\nn. 展览"),
            ("distinct", "adj. 明显的；独特的"),
            ("distinguish", "v. 区分；辨别"),
            ("distribute", "v. 分配；分发"),
            ("diverse", "adj. 多样的"),
            ("domestic", "adj. 国内的"),
            ("dominate", "v. 主导；支配"),
            ("dramatic", "adj. 戏剧性的"),
            ("duration", "n. 持续时间"),
            ("dynamic", "adj. 动态的\nn. 动力"),
        ],
        4: [
            ("First and foremost", "首先，最重要的是"),
            ("It is widely acknowledged that", "人们普遍认为"),
            ("There is no denying that", "不可否认的是"),
            ("It goes without saying that", "不言而喻"),
            ("As far as I am concerned", "就我而言"),
            ("From my perspective", "从我的角度来看"),
            ("To put it another way", "换句话说"),
            ("On the contrary", "相反地"),
            ("In contrast", "相比之下"),
            ("As a matter of fact", "事实上"),
            ("In the final analysis", "归根结底"),
            ("Last but not least", "最后但同样重要"),
            ("In conclusion", "总之"),
            ("It is imperative that", "当务之急是"),
            ("Play a significant role in", "在……中起重要作用"),
            ("Give rise to", "导致；引起"),
            ("Take into account", "考虑到"),
            ("Be attributed to", "归因于"),
            ("Be confronted with", "面临；面对"),
        ],
        5: [
            ("account for", "解释；占……比例"),
            ("ascribe to", "归因于"),
            ("attribute to", "归因于"),
            ("break down", "分解；出故障"),
            ("bring about", "引起；导致"),
            ("by contrast", "相比之下"),
            ("carry out", "执行；实施"),
            ("come up with", "提出；想出"),
            ("consist of", "由……组成"),
            ("contribute to", "有助于；导致"),
            ("depend on", "依赖；取决于"),
            ("draw on", "利用；凭借"),
            ("engage in", "从事；参与"),
            ("figure out", "弄明白；计算出"),
            ("give rise to", "引起；导致"),
            ("in terms of", "就……而言"),
            ("lay off", "解雇；停止"),
            ("make sense", "有意义；讲得通"),
            ("point of view", "观点；看法"),
            ("put forward", "提出；推荐"),
            ("refer to", "参考；指的是"),
            ("result in", "导致；造成"),
            ("set about", "开始；着手"),
            ("take over", "接管；接收"),
            ("turn out", "结果是；生产"),
            ("work out", "解决；制定出"),
        ],
        6: [
            ("on the whole", "总的来说"),
            ("in general", "一般来说"),
            ("for instance", "例如"),
            ("such as", "比如"),
            ("as a result", "因此"),
            ("in addition", "此外"),
            ("furthermore", "而且；此外"),
            ("nevertheless", "然而；不过"),
            ("nonetheless", "尽管如此"),
            ("otherwise", "否则；不然"),
            ("provided that", "假如；如果"),
            ("regardless of", "不管；不顾"),
            ("in spite of", "尽管"),
            ("due to", "由于"),
            ("owing to", "因为；由于"),
            ("thanks to", "幸亏；由于"),
            ("with respect to", "关于；至于"),
            ("on behalf of", "代表"),
            ("in favor of", "支持；赞成"),
            ("in light of", "鉴于；根据"),
        ],
    }

    politics_cards = {
        1: [
            ("马克思主义的创立", "1848年《共产党宣言》发表，标志着马克思主义的诞生。"),
            ("马克思主义的基本特征", "科学性、革命性、实践性、人民性和发展性。"),
            ("物质与意识的关系", "物质决定意识，意识对物质具有能动的反作用。"),
            ("唯物辩证法总特征", "联系的观点和发展的观点。"),
            ("对立统一规律", "事物发展的根本规律，是唯物辩证法的实质和核心。"),
            ("质量互变规律", "量变是质变的必要准备，质变是量变的必然结果。"),
            ("否定之否定规律", "事物发展是前进性和曲折性的统一。"),
            ("实践是认识的基础", "实践是认识的来源、动力、目的和检验标准。"),
            ("真理的绝对性与相对性", "真理是具体的、有条件的；绝对真理与相对真理辩证统一。"),
            ("社会存在与社会意识", "社会存在决定社会意识，社会意识具有相对独立性。"),
            ("生产力与生产关系", "生产力决定生产关系，生产关系反作用于生产力。"),
            ("经济基础与上层建筑", "经济基础决定上层建筑，上层建筑反作用于经济基础。"),
            ("社会基本矛盾", "生产力与生产关系的矛盾、经济基础与上层建筑的矛盾。"),
            ("人民群众是历史的创造者", "人民群众是社会物质财富、精神财富的创造者，是社会变革的决定力量。"),
            ("商品二因素", "商品是使用价值和价值的统一体。"),
            ("劳动二重性", "具体劳动创造使用价值，抽象劳动创造价值。"),
            ("价值规律", "商品的价值量由社会必要劳动时间决定，等价交换。"),
            ("剩余价值", "资本家剥削工人创造的超过劳动力价值的那部分价值。"),
            ("资本循环与周转", "产业资本依次经过购买、生产、销售三个阶段。"),
            ("资本主义基本矛盾", "生产社会化与生产资料资本主义私人占有之间的矛盾。"),
        ],
        2: [
            ("毛泽东思想的形成", "1945年中共七大确立毛泽东思想为党的指导思想。"),
            ("新民主主义革命总路线", "无产阶级领导的，人民大众的，反对帝国主义、封建主义和官僚资本主义的革命。"),
            ("新民主主义三大纲领", "政治纲领：建立无产阶级领导的各革命阶级联合专政；经济纲领：没收封建地主土地归农民所有；文化纲领：民族的科学的大众的文化。"),
            ("中国革命道路", "农村包围城市、武装夺取政权。"),
            ("三大法宝", "统一战线、武装斗争、党的建设。"),
            ("社会主义改造", "对农业、手工业和资本主义工商业的社会主义改造。"),
            ("社会主义初级阶段", "我国正处于并将长期处于社会主义初级阶段。"),
            ("习近平新时代中国特色社会主义思想", "是马克思主义中国化的最新成果，是当代中国马克思主义、21世纪马克思主义。"),
            ("中国式现代化", "人口规模巨大、全体人民共同富裕、物质文明和精神文明相协调、人与自然和谐共生、走和平发展道路的现代化。"),
            ("新发展理念", "创新、协调、绿色、开放、共享。"),
            ("新发展格局", "以国内大循环为主体、国内国际双循环相互促进。"),
            ("高质量发展", "是全面建设社会主义现代化国家的首要任务。"),
            ("总体国家安全观", "以人民安全为宗旨，以政治安全为根本。"),
            ("全过程人民民主", "社会主义民主政治的本质属性。"),
            ("一带一路", "丝绸之路经济带和21世纪海上丝绸之路。"),
        ],
        3: [
            ("鸦片战争", "1840年，中国近代史的开端，标志着中国开始沦为半殖民地半封建社会。"),
            ("太平天国运动", "1851-1864年，农民阶级的反封建反侵略斗争。"),
            ("洋务运动", "1860-1890年代，\"自强\"\"求富\"，是中国近代化的起步。"),
            ("戊戌变法", "1898年，资产阶级维新派发起的救亡图存运动。"),
            ("辛亥革命", "1911年，孙中山领导的资产阶级民主革命，推翻封建帝制。"),
            ("五四运动", "1919年，新民主主义革命的开端，标志着中国工人阶级登上政治舞台。"),
            ("中共一大", "1921年，中国共产党成立。"),
            ("南昌起义", "1927年8月1日，打响武装反抗国民党反动派第一枪。"),
            ("遵义会议", "1935年，确立毛泽东的领导地位，是党的历史上生死攸关的转折点。"),
            ("抗日战争", "1931-1945年，中国近代以来第一次取得完全胜利的民族解放战争。"),
            ("开国大典", "1949年10月1日，中华人民共和国成立。"),
            ("改革开放", "1978年十一届三中全会，开启了改革开放和社会主义现代化建设新时期。"),
            ("南方谈话", "1992年邓小平南方谈话，推动改革开放进入新阶段。"),
            ("香港回归", "1997年7月1日，中华人民共和国恢复对香港行使主权。"),
            ("澳门回归", "1999年12月20日，中华人民共和国恢复对澳门行使主权。"),
        ],
        4: [
            ("社会主义核心价值观", "富强、民主、文明、和谐；自由、平等、公正、法治；爱国、敬业、诚信、友善。"),
            ("社会主义道德核心", "为人民服务是社会主义道德的核心。"),
            ("社会主义道德原则", "集体主义是社会主义道德的原则。"),
            ("中华民族精神", "以爱国主义为核心的团结统一、爱好和平、勤劳勇敢、自强不息。"),
            ("时代精神", "以改革创新为核心。"),
            ("法律的本质", "法律是统治阶级意志的体现，是由国家制定或认可的行为规范。"),
            ("宪法基本原则", "党的领导原则、人民主权原则、尊重和保障人权原则、民主集中制原则、法治原则。"),
            ("公民基本权利", "平等权、政治权利、人身自由、社会经济权利、文化教育权利等。"),
            ("公民基本义务", "维护国家统一和民族团结、遵守宪法法律、依法纳税等。"),
            ("全面推进依法治国", "科学立法、严格执法、公正司法、全民守法。"),
            ("中国特色社会主义法治道路", "坚持党的领导、坚持人民主体地位、坚持法律面前人人平等。"),
            ("法治思维", "将法律作为判断是非和处理事务的准绳。"),
        ],
        5: [
            ("和平与发展", "当今时代的主题。"),
            ("经济全球化", "世界经济活动超越国界，通过对外贸易、资本流动等形成的相互依存、相互联系的趋势。"),
            ("多极化趋势", "世界格局向多极化方向发展，多个力量中心相互制衡。"),
            ("人类命运共同体", "倡导建设持久和平、普遍安全、共同繁荣、开放包容、清洁美丽的世界。"),
            ("全球治理观", "共商共建共享的全球治理观。"),
            ("新型国际关系", "相互尊重、公平正义、合作共赢。"),
            ("中国外交政策", "独立自主的和平外交政策。"),
            ("一带一路倡议", "秉持共商共建共享原则，推动政策沟通、设施联通、贸易畅通、资金融通、民心相通。"),
            ("文明交流互鉴", "文明因多样而交流，因交流而互鉴，因互鉴而发展。"),
            ("生物安全", "国家安全体系的重要组成部分。"),
        ],
    }

    hongbao_cards = [
        ("premium", "/ˈpriːmiəm/", "n. 保险费；额外费用；奖金\nadj. 高级的；优质的",
         "You have to pay a premium for express delivery. 快递需付额外费用。",
         "【用法】at a premium 溢价；稀缺\n【同义】bonus, extra, superior"),
        ("obscure", "/əbˈskjʊər/", "adj. 模糊的；晦涩的；无名的\nv. 使模糊；掩盖",
         "His poetry is full of obscure references. 他的诗充满晦涩的引用。",
         "【用法】obscure poet 无名诗人\n【同义】vague, unclear, ambiguous\n【反义】clear, famous"),
        ("notorious", "/nəʊˈtɔːriəs/", "adj. 臭名昭著的；声名狼藉的",
         "The city is notorious for its traffic jams. 这个城市以交通堵塞闻名。",
         "【用法】be notorious for 因……而臭名昭著\n【同义】infamous, disreputable\n【反义】famous, renowned"),
        ("scrutiny", "/ˈskruːtəni/", "n. 仔细审查；监督",
         "The proposal is under close scrutiny. 这个提议正在被仔细审查。",
         "【用法】under scrutiny 受到审查\n【同义】examination, inspection, analysis"),
        ("allegation", "/ˌæləˈɡeɪʃn/", "n. 指控；断言；主张（尤指未经证实的）",
         "The allegations of corruption were denied. 腐败的指控被否认了。",
         "【用法】make an allegation 提出指控\n【同义】accusation, claim, assertion"),
        ("concede", "/kənˈsiːd/", "v. 承认；让步；允许",
         "He conceded that he had made a mistake. 他承认自己犯了错。",
         "【用法】concede defeat 承认失败\n【同义】admit, acknowledge, yield"),
        ("deteriorate", "/dɪˈtɪəriəreɪt/", "v. 恶化；退化；变质",
         "The situation deteriorated rapidly. 局势迅速恶化。",
         "【用法】deteriorate into 恶化为……\n【同义】worsen, decline, decay\n【反义】improve"),
        ("elaborate", "/ɪˈlæbərət/", "adj. 精心制作的；详尽的\nv. 详细说明；精心制作",
         "Could you elaborate on your plan? 你能详细说明你的计划吗？",
         "【用法】elaborate on 详细说明\n【同义】detailed, intricate, explain"),
        ("futile", "/ˈfjuːtaɪl/", "adj. 无效的；无用的；徒劳的",
         "All attempts were futile. 所有尝试都是徒劳的。",
         "【用法】futile attempt 徒劳的尝试\n【同义】useless, vain, pointless\n【反义】effective"),
        ("hamper", "/ˈhæmpər/", "v. 妨碍；阻碍；束缚",
         "The storm hampered rescue efforts. 暴风雨阻碍了救援工作。",
         "【用法】be hampered by 受……阻碍\n【同义】hinder, impede, obstruct\n【反义】facilitate"),
        ("inherent", "/ɪnˈhɪərənt/", "adj. 固有的；内在的；与生俱来的",
         "There are inherent risks in any investment. 任何投资都有固有风险。",
         "【用法】be inherent in 内在的；固有的\n【同义】intrinsic, innate, inborn"),
        ("jeopardize", "/ˈdʒepədaɪz/", "v. 危及；损害；使陷入危险",
         "The scandal jeopardized his career. 丑闻危及了他的职业生涯。",
         "【用法】jeopardize one's future 危及某人的前途\n【同义】endanger, threaten, risk"),
        ("legitimate", "/lɪˈdʒɪtɪmət/", "adj. 合法的；正当的\nv. 使合法",
         "Is that a legitimate concern? 那是合理的担忧吗？",
         "【用法】legitimate business 合法生意\n【同义】legal, lawful, valid\n【反义】illegitimate"),
        ("magnitude", "/ˈmæɡnɪtjuːd/", "n. 巨大；重要性；震级",
         "We underestimated the magnitude of the problem. 我们低估了问题的严重性。",
         "【用法】of great magnitude 至关重要的\n【同义】scale, extent, significance"),
        ("nominal", "/ˈnɒmɪnl/", "adj. 名义上的；象征性的；名词性的",
         "He is only the nominal head of the company. 他只是公司的名义负责人。",
         "【用法】nominal fee 象征性费用\n【同义】titular, symbolic, minimal"),
    ]

    hongbao_topic_ids = {
        1: 7, 2: 8, 3: 9, 4: 10, 5: 11, 6: 12, 7: 13,
    }

    for idx, card in enumerate(hongbao_cards):
        front, phonetic, back, example, back_detail = card
        cur.execute(
            f"INSERT INTO cards (topic_id, front, back, phonetic, example, back_detail, order_num) VALUES ({place},{place},{place},{place},{place},{place},{place})",
            (hongbao_topic_ids[1], front, back, phonetic, example, back_detail, idx + 1),
        )

    for topic_id, cards in english_cards.items():
        for idx, card_data in enumerate(cards):
            front = card_data[0]
            if len(card_data) == 2:
                back = card_data[1]; phonetic = ""; example = ""; back_detail = ""
            else:
                phonetic = card_data[1]; back = card_data[2]
                example = card_data[3] if len(card_data) > 3 else ""
                back_detail = card_data[4] if len(card_data) > 4 else ""
            cur.execute(
                f"INSERT INTO cards (topic_id, front, back, phonetic, example, back_detail, order_num) VALUES ({place},{place},{place},{place},{place},{place},{place})",
                (topic_id, front, back, phonetic, example, back_detail, idx + 1),
            )

    politics_offset = len(english_topics) + len(hongbao_topics)
    for topic_id, cards in politics_cards.items():
        for idx, card_data in enumerate(cards):
            front = card_data[0]
            back = card_data[1] if len(card_data) > 1 else ""
            cur.execute(
                f"INSERT INTO cards (topic_id, front, back, phonetic, example, back_detail, order_num) VALUES ({place},{place},{place},{place},{place},{place},{place})",
                (topic_id + politics_offset, front, back, "", "", "", idx + 1),
            )

    if DB_TYPE == "mysql":
        conn.commit()
